version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - /var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432
